# Force NB-IoT + GNSS for nRF9151.
CONFIG_LTE_NETWORK_MODE_LTE_M_NBIOT_GPS=n
CONFIG_LTE_NETWORK_MODE_NBIOT_GPS=y

# Optional: prioritize/lock operator for China Mobile.
# If your SIM belongs to another PLMN, update this value.
CONFIG_LTE_LOCK_PLMN=y
CONFIG_LTE_LOCK_PLMN_STRING="46000"
